# Generated by Django 4.1.7 on 2023-03-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='closing_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='days_open',
            field=models.CharField(blank=True, choices=[('SU', 'sunday'), ('M', 'monday'), ('T', 'tuesday'), ('W', 'wednesday'), ('TH', 'thursday'), ('F', 'friday'), ('SA', 'saturday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='open_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
