# Generated by Django 3.2.18 on 2023-03-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.event'),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.event'),
        ),
    ]
