# Generated by Django 4.1.7 on 2023-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0002_auto_20230316_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
