# Generated by Django 4.1.7 on 2023-03-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0002_touristspot_closing_time_touristspot_days_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='days_open',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='open_time',
        ),
    ]
