# Generated by Django 3.2.18 on 2023-03-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0003_remove_touristspot_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Feeding Room', 'Feeding Room'), ('Rest Room', 'Rest Room'), ('Wash Room', 'Wash Room'), ('Toilet', 'Toilet'), ('Waste Bin', 'Waste Bin')], max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.touristspot')),
            ],
        ),
    ]
