# Generated by Django 4.1.7 on 2023-03-19 03:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0003_remove_touristspot_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='booking_open',
        ),
        migrations.CreateModel(
            name='TouristTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$', 'Please enter a valid email')])),
                ('persons_count', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)])),
                ('parking_needed', models.BooleanField(default=False)),
                ('is_inside', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.touristspot')),
            ],
        ),
    ]
