# Generated by Django 4.1.7 on 2023-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0003_tickettier_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
