# Generated by Django 4.1.7 on 2023-03-17 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0005_ticket_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$', 'Please enter a valid email')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='persons_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.CreateModel(
            name='ParkingTicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('2 Wheeler', '2 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=150)),
                ('capacity', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.event')),
            ],
        ),
    ]
