# Generated by Django 4.1.7 on 2023-03-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0006_alter_ticket_email_alter_ticket_persons_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parking_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_admin.parkingtickettier'),
        ),
        migrations.AlterField(
            model_name='parkingtickettier',
            name='title',
            field=models.CharField(choices=[('2 Wheeler', '2 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=150, unique=True),
        ),
    ]
