# Generated by Django 4.1.7 on 2023-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0007_ticket_parking_tier_alter_parkingtickettier_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingtickettier',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
