# Generated by Django 4.1.7 on 2023-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0008_parkingtickettier_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('parking_available', models.BooleanField(default=False)),
                ('parking_max_capacity', models.IntegerField(blank=True, null=True)),
                ('booking_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parkingtickettier',
            name='location',
        ),
    ]
