# Generated by Django 4.1.7 on 2023-03-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0012_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
