# Generated by Django 4.1.7 on 2023-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0013_remove_event_image'),
        ('ticket_admin', '0013_ticket_qr_code'),
    ]

    operations = [
    ]
